services:
  runner:
    build:
      context: .
      args:
        RUNNER_VERSION: ${RUNNER_VERSION}
    privileged: true
    environment:
      REPO_URL:       ${REPO_URL}
      RUNNER_TOKEN:   ${RUNNER_TOKEN}
      RUNNER_NAME:    ${RUNNER_NAME}
      RUNNER_WORKDIR: ${RUNNER_WORKDIR:-_work}
    volumes:
      - runner-work:/actions-runner/_work
      - dind-data:/var/lib/docker
    restart: unless-stopped

volumes:
  runner-work:
  dind-data: