services:
  runner:
    build:
      context: .
      args:
        RUNNER_VERSION: ${RUNNER_VERSION}
    environment:
      REPO_URL:       ${REPO_URL}
      RUNNER_TOKEN:   ${RUNNER_TOKEN}
      RUNNER_NAME:    ${RUNNER_NAME}
      RUNNER_WORKDIR: ${RUNNER_WORKDIR:-_work}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - runner-work:/actions-runner/_work
    restart: unless-stopped

volumes:
  runner-work:
