name: Publish Runner Image (SHA & Latest)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    outputs:
      registry: ${{ steps.downcase.outputs.registry }}

    steps:
      - id: downcase
        name: Downcase owner for registry
        shell: bash
        run: |
          OWNER="${{ github.repository_owner }}"
          echo "registry=ghcr.io/${OWNER,,}" >>"$GITHUB_OUTPUT"

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push runner package to ghcr.io
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64
          cache-from: type=registry,ref=${{ steps.downcase.outputs.registry }}/runner:buildcache
          cache-to: type=registry,ref=${{ steps.downcase.outputs.registry }}/runner:buildcache,mode=max
          tags: |
            ${{ steps.downcase.outputs.registry }}/runner:${{ github.sha }}
            ${{ steps.downcase.outputs.registry }}/runner:latest
